"""SQL schema for init-db command."""

from __future__ import annotations

from gnosis_mcp.config import GnosisMcpConfig

__all__ = ["SCHEMA_SQL", "get_init_sql"]

SCHEMA_SQL = """\
-- Gnosis MCP documentation schema
-- Generated by: gnosis-mcp init-db

CREATE SCHEMA IF NOT EXISTS {schema};

-- pgvector extension (requires superuser; skip if already installed)
CREATE EXTENSION IF NOT EXISTS vector;

-- Documentation chunks table
CREATE TABLE IF NOT EXISTS {schema}.{chunks_table} (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_path text NOT NULL,
    chunk_index integer NOT NULL DEFAULT 0,
    title text,
    content text NOT NULL,
    category text,
    audience text DEFAULT 'all',
    tags text[],
    embedding vector({embedding_dim}),
    tsv tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(title, '') || ' ' || content)
    ) STORED,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    UNIQUE (file_path, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_{chunks_table}_file_path
    ON {schema}.{chunks_table} (file_path);
CREATE INDEX IF NOT EXISTS idx_{chunks_table}_category
    ON {schema}.{chunks_table} (category);
CREATE INDEX IF NOT EXISTS idx_{chunks_table}_tsv
    ON {schema}.{chunks_table} USING gin (tsv);

-- Documentation links table
CREATE TABLE IF NOT EXISTS {schema}.{links_table} (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source_path text NOT NULL,
    target_path text NOT NULL,
    relation_type text NOT NULL DEFAULT 'related',
    created_at timestamptz DEFAULT now(),
    UNIQUE (source_path, target_path, relation_type)
);

CREATE INDEX IF NOT EXISTS idx_{links_table}_source
    ON {schema}.{links_table} (source_path);
CREATE INDEX IF NOT EXISTS idx_{links_table}_target
    ON {schema}.{links_table} (target_path);

-- Basic keyword search function (no embeddings required)
CREATE OR REPLACE FUNCTION {schema}.search_{chunks_table}(
    p_query_text text,
    p_categories text[] DEFAULT NULL,
    p_limit integer DEFAULT 5
)
RETURNS TABLE (
    file_path text,
    title text,
    content text,
    category text,
    combined_score double precision
)
LANGUAGE sql STABLE
AS $$
    SELECT
        c.file_path,
        c.title,
        c.content,
        c.category,
        ts_rank(c.tsv, websearch_to_tsquery('english', p_query_text))::double precision AS combined_score
    FROM {schema}.{chunks_table} c
    WHERE c.tsv @@ websearch_to_tsquery('english', p_query_text)
      AND (p_categories IS NULL OR c.category = ANY(p_categories))
    ORDER BY combined_score DESC
    LIMIT p_limit;
$$;
"""


def get_init_sql(config: GnosisMcpConfig) -> str:
    """Interpolate config values into the schema SQL template.

    Note: init-db always creates tables with standard column names (file_path,
    title, content, etc.). GNOSIS_MCP_COL_* overrides are for querying existing
    tables with non-standard column names -- they do not affect init-db.
    """
    return SCHEMA_SQL.format(
        schema=config.schema,
        chunks_table=config.chunks_tables[0],
        links_table=config.links_table,
        embedding_dim=config.embedding_dim,
    )
